app/findshows/urls.py
from functools import partial

from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "findshows"
urlpatterns = [
    path("", views.home, name="home"),
    path("user_settings", views.user_settings, name="user_settings"),
    path('about/', TemplateView.as_view(template_name='findshows/pages/about.html'), name="about"),
    path('artist_faq/', TemplateView.as_view(template_name='findshows/pages/artist_faq.html'), name="artist_faq"),
    path('contact/', views.contact, name="contact"),

    path("artist/<int:pk>", views.view_artist, name="view_artist"),
    path("artist/<int:pk>/edit", views.edit_artist, name="edit_artist"),
    path("artist_dashboard", views.artist_dashboard, name="artist_dashboard"),
    path("link_artist", views.link_artist, name="link_artist"),

    path("concert/<int:pk>", views.view_concert, name="view_concert"),
    path("concert/<int:pk>/edit", views.edit_concert, name="edit_concert"),
    path("concert/create", views.edit_concert, name="create_concert"),
    path("concert/<int:pk>/cancel", views.cancel_concert, name="cancel_concert"),
    path("concert/<int:pk>/uncancel", partial(views.cancel_concert, uncancel=True), name="uncancel_concert"),

    path("mod_dashboard", views.mod_dashboard, name="mod_dashboard"),
    path("htmx/mod_daily_digest", views.mod_daily_digest, name="mod_daily_digest"),
    path("htmx/mod_queue", views.mod_queue, name="mod_queue"),
    path("htmx/mod_outstanding_invites", views.mod_outstanding_invites, name="mod_outstanding_invites"),
    path("htmx/venue_verification/<int:pk>", views.venue_verification, name="venue_verification"),
    path("htmx/resend_invite/<int:pk>", views.resend_invite, name="resend_invite"),
    path("htmx/approve_artist_request/<int:pk>", views.approve_artist_request, name="approve_artist_request"),

    path("htmx/concert_search/", views.concert_search, name="concert_search"),

    path("htmx/mb_artist_search_results/", views.musicbrainz_artist_search_results, name="musicbrainz_artist_search_results"),
    path("htmx/venue_search_results/", views.venue_search_results, name="venue_search_results"),
    path("htmx/create_venue/", views.create_venue, name="create_venue"),
    path("htmx/create_temp_artist/", views.create_temp_artist, name="create_temp_artist"),
    path("htmx/request_artist_access/", views.request_artist_access, name="request_artist_access"),
    path("htmx/manage_artist_access/<int:pk>", views.manage_artist_access, name="manage_artist_access"),
    path("htmx/artist_search_results/", views.artist_search_results, name="artist_search_results"),
]

app/localmusic/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from findshows import views

urlpatterns = [
    path('', include("findshows.urls")),

    path('admin/', admin.site.urls),

    path("accounts/", include("django.contrib.auth.urls")),
    # accounts/login/ [name='login']
    # accounts/logout/ [name='logout']
    # accounts/password_change/ [name='password_change']
    # accounts/password_change/done/ [name='password_change_done']
    # accounts/password_reset/ [name='password_reset']
    # accounts/password_reset/done/ [name='password_reset_done']
    # accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
    # accounts/reset/done/ [name='password_reset_complete']
    path("accounts/create_account", views.create_account, name='create_account'),
    path("accounts/verify_email", views.verify_email, name='verify_email'),
    path("accounts/resend_email_verification", views.resend_email_verification, name='resend_email_verification'),

    path('captcha/', include("captcha.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/findshows/views.py
from datetime import timedelta
from operator import and_, or_
from functools import reduce
import json
from random import random, shuffle
from pymemcache.client.base import Client

from django.contrib.auth import login
from django.core.exceptions import PermissionDenied
from django.db import IntegrityError
from django.urls import reverse
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.postgres.search import TrigramSimilarity
from django.db.models import Q
from django.utils import timezone
from django.views.generic.dates import timezone_today
from django.conf import settings

from findshows.email import contact_email, invite_artist, invite_user_to_artist, send_artist_setup_info, send_verify_email
from findshows.widgets import ArtistAccessWidget

from .models import Artist, ArtistLinkingInfo, Concert, ConcertTags, EmailCodeError, EmailVerification, InviteDelayError, JPEGImageException, MusicBrainzArtist, Venue
from .forms import ArtistAccessForm, ArtistEditForm, ConcertForm, ContactForm, ModDailyDigestForm, RequestArtistForm, ShowFinderForm, TempArtistForm, UserCreationFormE, UserProfileForm, VenueForm


#################
## User Views ###
#################

def contact(request):
    success = False
    if request.POST:
        form = ContactForm(request.POST)

        if form.is_valid():
            memcache_client = Client(settings.MEMCACHE_LOCATION, timeout=3, connect_timeout=3)
            recent_contacts = memcache_client.incr('num_recent_contacts', 1)
            if recent_contacts is None:
                memcache_client.set('num_recent_contacts', 1, 60, True)
                recent_contacts = 1

            if recent_contacts > settings.MAX_CONTACTS_PER_MINUTE:
                form.add_error(None, "High contact volume; please try again in a minute. This is a spam prevention measure, thanks for understanding.")
            elif contact_email(form):
                success = True
                form = ContactForm()
    else:
        form = ContactForm()

    return render(request, "findshows/pages/contact.html", context={
        "form": form,
        "success": success
    })


@login_required
def user_settings(request):
    if request.POST:
        form = UserProfileForm(request.POST, instance=request.user.userprofile)
        if form.is_valid():
            form.save()
            return redirect('findshows:home')
    else:
        form = UserProfileForm(instance=request.user.userprofile)

    return render(request, "findshows/pages/user_settings.html", context={
        "form": form,
        "is_local_artist_account": is_local_artist_account(request.user)
    })


def create_account(request):
    if request.method != 'POST':
        user_form = UserCreationFormE()
        profile_form = UserProfileForm()
        next = request.GET.get('next')
    else:
        user_form = UserCreationFormE(request.POST)
        profile_form = UserProfileForm(request.POST)
        next = request.POST.get('next')

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()

            email_verification, invite_code = EmailVerification.create_and_get_invite_code(user.email)
            if not send_verify_email(email_verification, invite_code, profile_form):
                # Info about verification (failure or otherwise) will be shown
                # to the user in a banner on the home search page
                email_verification.delete()

            if "sendartistinfo" in request.POST:
                send_artist_setup_info(user.email)
            login(request, user)
            if next:
                return redirect(next)
            else:
                return redirect('findshows:home')

    context = {'user_form': user_form,
               'profile_form': profile_form,
               'next': next,
               }

    return render(request, 'registration/create_account.html', context)


@login_required
def verify_email(request):
    try:
        email_verification = EmailVerification.check_url(request.GET, request.user.email)
    except EmailCodeError as e:
        return render(request, "findshows/pages/email_verification.html",
                      {'error': e.message})

    request.user.userprofile.email_is_verified = True
    request.user.userprofile.save()
    email_verification.delete()

    return render(request, "findshows/pages/email_verification.html")


@login_required
def resend_email_verification(request):
    errorlist = []
    if request.user.userprofile.email_is_verified:
        errorlist.append("Email already verified.")
    else:
        try:
            email_verification = EmailVerification.objects.get(invited_email=request.user.email)
            invite_code = email_verification.regenerate_invite_code()
        except EmailVerification.DoesNotExist:
            email_verification, invite_code = EmailVerification.create_and_get_invite_code(request.user.email)

        if not send_verify_email(email_verification, invite_code, errorlist=errorlist):
            email_verification.delete()

    success = not errorlist

    return render(request, "findshows/htmx/email_verification_banner.html", {
        'success': success,
        'errorlist': errorlist,
    })

###################
## Artist Views ###
###################

def is_artist_account(user):
    return (not user.is_anonymous
            and len(user.userprofile.managed_artists.all()) > 0)


def is_local_artist_account(user):
    return (not user.is_anonymous
            and any(a.local for a in user.userprofile.managed_artists.all()) > 0)


def has_edit_privileges(user):
    return ((is_local_artist_account(user) and user.userprofile.email_is_verified) or
            is_mod(user))


@user_passes_test(is_artist_account)
def artist_dashboard(request):
    artists=request.user.userprofile.managed_artists.all()
    # Remove duplicates in case user manages multiple artists on same bill
    concerts = set(c for a in artists for c in a.concert_set.filter(date__gte=timezone_today()))
    concerts = sorted(concerts, key = lambda c: c.date)

    return render(request, "findshows/pages/artist_dashboard.html", context = {
        "artists": artists,
        "concerts": concerts,
        "is_local_artist": is_local_artist_account(request.user)
    })


def view_artist(request, pk):
    artist = get_object_or_404(Artist, pk=pk)
    can_edit = (not request.user.is_anonymous
                and artist in request.user.userprofile.managed_artists.all())

    if artist.is_temp_artist and not can_edit:
        raise PermissionDenied

    upcoming_concerts = Concert.objects.all() if can_edit else Concert.publically_visible()
    upcoming_concerts = upcoming_concerts.filter(date__gte=timezone.now(), artists=artist)

    return render(request, "findshows/pages/view_artist.html", context={
        'artist': artist,
        'can_edit': can_edit,
        'upcoming_concerts': upcoming_concerts
    })


@login_required
def edit_artist(request, pk):
    artist = get_object_or_404(Artist, pk=pk)
    if artist not in request.user.userprofile.managed_artists.all():
        raise PermissionDenied

    if request.method != 'POST':
        form = ArtistEditForm(instance=artist)
    else:
        form = ArtistEditForm(request.POST, request.FILES, instance=artist)
        if form.is_valid():
            try:
                form.save()
                return redirect(reverse('findshows:view_artist', args=[pk]))
            except JPEGImageException as e:
                form.add_error('profile_picture', e.message)

    context = {'form': form,
               'pk': pk,
               'is_temp_artist': artist.is_temp_artist}

    return render(request, 'findshows/pages/edit_artist.html', context)


def artist_search_results(request):
    if not (request.GET and request.GET["artist-search"] and request.GET["idx"]):
        return HttpResponse("")

    keywords = request.GET["artist-search"].split()
    idx = int(request.GET["idx"])

    search_results = Artist.objects.filter(
        reduce(and_, (Q(name__icontains=k) for k in keywords))
    )[:5]
    return render(request, "findshows/htmx/artist_search_results.html", {
        "artists": search_results,
        "idx": idx
    })


def has_exceeded_daily_invites(user):
    return (not is_mod(user) and
            records_created_today(ArtistLinkingInfo, user.userprofile) >= settings.MAX_DAILY_INVITES)

def is_new_artist_account(user):
    if is_mod(user):
        return False
    return (not user.userprofile.given_artist_access_datetime or
            user.userprofile.given_artist_access_datetime > timezone.now() - timedelta(settings.INVITE_BUFFER_DAYS))

def create_temp_artist(request):
    if not (has_edit_privileges(request.user)):
        return render(request, 'findshows/htmx/cant_create_artist.html', {
            'no_privileges': True
        })

    if has_exceeded_daily_invites(request.user):
        return render(request, 'findshows/htmx/cant_create_artist.html')

    if is_new_artist_account(request.user):
        return render(request, 'findshows/htmx/cant_create_artist.html', context={'new_account_delay': settings.INVITE_BUFFER_DAYS})

    # The latter condition is a slightly hacky way of telling whether this HTMX
    # request is being triggered by page load (we should provide blank form) or
    # click (we should process form and display errors if they exist)
    if request.POST and 'temp_artist-name' in request.POST:
        form = TempArtistForm(request.POST)
    else:
        form = TempArtistForm()

    valid = form.is_valid()
    if valid:
        artist = form.save(commit=False)
        artist.created_by = request.user.userprofile
        artist.save()

app/findshows/templates/findshows/widgets/artist_access_widget.html
{% comment %}
The user json has two properties, 'email' and 'type'.
Valid values for 'type' are defined in findshows.widgets.ArtistAccessWidget.Types
{% endcomment %}

<div class="flex flex-col items-center justify-center"
     x-data="artist_access_data()"
     x-init="artist_access_init({{widget.value}})" {# don't need |escapejs because it's already encoded as JSON? #}
     x-cloak>

    <input type="hidden" name="{{widget.name}}" :value="JSON.stringify(users)">

    <div class="flex flex-col w-full p-4 h-full">
        <div> Add user by email: </div>
        <div class="flex">
            <input type="text" class="w-full textinput" x-model="new_email" >
            <button class="btn px-4" type="button" @click="add_user()"> Add </button>
        </div>
        <div class="pt-4"> Users with access: </div>
        <ol class="w-full">
            <template x-for="(user, idx) in users" :key="idx">
                <li class="flex w-full justify-between my-2">
                    <div class="my-auto"
                         :class="is_removed(user) ? 'line-through' : ''" x-text="user.email"> </div>
                    <div class="flex justify-around flex-wrap">
                        <template x-if="!is_removed(user)">
                            <button class="btn px-1" type="button" @click="remove_user(idx)">
                                Remove
                            </button>
                        </template>
                        <template x-if="is_removed(user)">
                            <button class="btn px-1" type="button" @click="restore_user(idx)">
                                Restore
                            </button>
                        </template>
                        <template x-if="is_unlinked(user)">
                            <button class="btn px-1 sm:min-w-40" type="button" @click="resend_user(idx)">
                                Re-send invite
                            </button>
                        </template>
                        <template x-if="is_resend(user)">
                            <button class="btn px-1 min-w-40" type="button" @click="unresend_user(idx)">
                                Undo re-send
                            </button>
                        </template>
                    </div>
                </li>
            </template>
            <template x-if="!users">
                <div>
                    No other users have acess to this artist.
                </div>
            </template>
        </ol>
    </div>
</div>

<script>
 function artist_access_data() {
     return {
         new_email: '',
         users: [],

         artist_access_init(initial_widget_val) {
             this.users = initial_widget_val;
         },

         add_user() {
             user = {
                 'email': this.new_email,
                 'type': 'NEW',
             };
             this.users.push(user);
             this.new_email = '';
         },

         remove_user(idx) {
             if (this.users[idx].type === 'NEW') {
                 this.users.splice(idx, 1);
             }
             else {
                 this.users[idx].initial_type = this.users[idx].type
                 this.users[idx].type='REMOVED';
            }
         },

         restore_user(idx) {
             this.users[idx].type = this.users[idx].initial_type
         },

         resend_user(idx) {
             this.users[idx].type = 'RESEND'
         },

         unresend_user(idx) {
             this.users[idx].type = 'UNLINKED'
         },

         is_removed(user) {
             return user.type=='REMOVED'
         },

         is_unlinked(user) {
             return user.type=='UNLINKED'
         },

         is_resend(user) {
             return user.type=='RESEND'
         },


     }
 }
</script>

app/findshows/templates/findshows/widgets/bill_widget.html
{% load static %}

<div class="flex flex-col items-center justify-center"
     x-data="bill_data()"
     x-init="bill_init({{widget.value}})" {# don't need |escapejs because it's already encoded as JSON? #}
     x-cloak>

    <div class="flex w-full p-2 h-full items-center">

        <input type="hidden" name="{{widget.name}}" :value="JSON.stringify(bill_order)">

        <ol id="bill-editor" class="w-full">
            <template x-for="(artist, idx) in bill_order" :key="idx">
                <li class="flex w-full max-w-lg justify-between my-2"
                    x-init="$nextTick(() => htmx.process($el))"> {# necessary for any HTMX in an x-for #}
                    <div class="w-full"
                         @focusin="open_dropdown(artist)"
                         @click.outside="close_dropdown(artist)"
                    >
                        <input class="textinput w-full" type="search"
                               id="artist-search-field"
                               name="artist-search" placeholder="Select an artist..."
                               x-model="artist.search_text"
                               hx-get="{% url 'findshows:artist_search_results' %}"
                               :hx-vals="JSON.stringify({'idx': idx})"
                               hx-trigger="keyup changed delay:500ms"
                               hx-target="next #artist-search-results"
                        >
                        <ul id="artist-search-results"
                            class="absolute popup-menu"
                            x-show="artist.show_search"
                            @click="close_dropdown(artist)"
                            style="display: none;"
                        >
                        </ul>
                    </div>

                    <div class="flex justify-around w-21 ml-2">
                        {# Up arrow #}
                        <svg class="clickable-svg fill-current w-7"
                             viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg"
                             @click="move_artist(idx, -1)">
                            <path d="M17.504 26.025l.001-14.287 6.366 6.367L26 15.979 15.997 5.975 6 15.971 8.129 18.1l6.366-6.368v14.291z"/>
                        </svg>
                        {# Down arrow #}
                        <svg class="clickable-svg fill-current w-7"
                             viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg"
                             @click="move_artist(idx, 1)">
                            <path d="M14.496 5.975l-.001 14.287-6.366-6.367L6 16.021l10.003 10.004L26 16.029 23.871 13.9l-6.366 6.368V5.977z"/></svg>
                        {# Remove button #}
                        <svg class="clickable-svg fill-current w-7 stroke-3"
                             viewBox="0 0 18 18" xmlns="http://www.w3.org/2000/svg"
                             @click="remove_artist(idx)">
                            <path d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z"></path>
                        </svg>
                    </div>
                </li>
            </template>
            <li class="btn" @click="add_artist()"> Add set</li>
        </ol>
    </div>

    <div @modal-form-success="on_temp_artist_create">
        {% with title_text="Invite Artist" success_text="Invite sent successfully!" form_html="findshows/htmx/temp_artist_form.html" htmx_url="findshows:create_temp_artist" %}
            {% include "findshows/partials/modal_form.html" %}
        {% endwith %}
    </div>

</div>

<script src='{% static "findshows/js/bill_data.js" %}'></script>

app/findshows/templates/findshows/widgets/date_picker.html
{% load static %}

<div class="max-w-48 container py-1 relative"
     x-data="datePickerData({{ widget.allow_past_or_future }})"
     x-init="[initDate('{{ widget.value }}'), incrementCalDisplay(0)]"
     x-cloak
>
    <input type="hidden" name={{ widget.name }} :value="getWidgetReturnVal()">
    <input
        type="text"
        @click="showDatepicker = !showDatepicker"
        :value="getDisplayDate()"
        @keydown.escape="showDatepicker = false"
        class="textinput w-full cursor-pointer"
        placeholder="Select date"
        readonly>

    {# Popup menu #}
    <div class="popup-menu mt-12 w-64 p-4 absolute top-0 left-0"
         x-show.transition="showDatepicker"
         @click.away="showDatepicker = false">

        {# Header of date form #}
        <div class="flex justify-between items-center mb-2">
            <div class="flex justify-between items-center grow mr-2">
                <div x-text="MONTH_NAMES[calMonth-1]" class="text-lg font-semibold"></div>
                <div x-text="calYear" class="ml-1 text-lg text-gray-600 font-normal"></div>
            </div>
            <div class="flex justify-between">
                <button
                    type="button"
                    class="clickable-svg transition ease-in-out duration-100 p-1"
                    @click="incrementCalDisplay(-1)">
                    <svg class="h-6 w-6"  fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-width="2" d="M15 19l-7-7 7-7"/>
                    </svg>
                </button>
                <button
                    type="button"
                    class="clickable-svg transition ease-in-out duration-100 p-1"
                    @click="incrementCalDisplay(1)">
                    <svg class="h-6 w-6"  fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-width="2" d="M9 5l7 7-7 7"/>
                    </svg>
                </button>
            </div>
        </div>

        {# Grid of dates #}
        <div class="grid grid-cols-7 grid-flow-row -mx-1">
            <template x-for="day in DAYS">
                <div class="mb-1">
                    <div x-text="day" class="text-gray-800 font-medium text-center text-xs"></div>
                </div>
            </template>
            <template x-for="i in NumSpacesBeforeDays">
                <div ></div>
            </template>
            <template x-for="date in numDaysInMonth">
                <div class="px-1 mb-1">
                    <div
                        @click="onDateClick(date)"
                        x-text="date"
                        class="text-center text-sm leading-loose transition ease-in-out duration-100"
                        :class="{'text-gray-400': !isSelectable(date),
                                'bg-highlight-item-light cursor-pointer': isSelected(date),
                                'clickable-svg': isSelectable(date)&&(!isSelected(date)),
                                'font-bold': isToday(date)}"
                    ></div>
                </div>
            </template>
        </div>
    </div>
</div>

{# Script loaded in base.html because idk weird shit happening in mod dashboard #}

app/findshows/templates/findshows/widgets/image_widget.html
<div class="flex">
    {% if widget.is_initial %}
        <div class="flex flex-col">
            <div> {{ widget.initial_text }}: </div>
            <img class="max-h-36 max-w-36 m-2" src="{{ widget.value.url }}"/>
            {% if not widget.required %}
                <input type="checkbox" name="{{ widget.checkbox_name }}" id="{{ widget.checkbox_id }}"
                       {% if widget.attrs.disabled %} disabled{% endif %}
                       {% if widget.attrs.checked %} checked{% endif %}>
                <label for="{{ widget.checkbox_id }}">{{ widget.clear_checkbox_label }}</label>
            {% endif %}
        </div>
    {% endif %}
    <div class="flex flex-col w-full ml-2">
        <div> {{ widget.input_text }}: </div>
        <div class="relative m-2"
             x-data="{'new_file_name': ''}">
            <input class="opacity-0 h-0.5 w-0.5 absolute" type="{{ widget.type }}" name="{{ widget.name }}"
                   {% include "django/forms/widgets/attrs.html" %}
                   @change="new_file_name=$event.target.files[0].name">
            <label class="btn block m-0" for="{{ widget.attrs.id }}">
                Select file
            </label>
            <p x-text="new_file_name"></p>
        </div>
    </div>
</div>

app/findshows/templates/findshows/widgets/musicbrainz_artist_search.html
{% load static %}

<div x-data="musicbrainz_artist_search_data({{ widget.artist_dicts }},{{ widget.max_artists }})"
     @keydown.escape.prevent.stop="close_dropdown()"
     {#  @add-musicbrainz-card="add_rough_to_node($el.getElementById($event.detail.id))" #}
     @add-musicbrainz-card="$nextTick(() => add_rough_to_node(document.getElementById($event.detail.id)))"
>

    <div x-ref="musicbrainz-search-plus-dropdown"
         @focusin="open_dropdown()"
         @click.outside="close_dropdown()"
         @htmx:after-request="open_dropdown()"
    >
            <input class="textinput" type="search"
                   name="mb_search" placeholder="Search artists..."
                   x-model="search_text"
                   hx-get="{% url 'findshows:musicbrainz_artist_search_results' %}"
                   hx-trigger="keyup changed delay:500ms, click from:#search-results"
                   hx-target="#musicbrainz-search-results"
                   hx-swap="innerHTML"
                   hx-include="this"
            >

            <ul id="musicbrainz-search-results"
                class="absolute popup-menu"
                x-show="show_search"
                @click="close_dropdown()"
                style="display: none;"
            >
            </ul>
    </div>

    <div class="flex flex-wrap">
        <template x-for="(musicbrainz_artist, index) in selected_musicbrainz_artists" :key="index">
            <div>
                {% include "../partials/musicbrainz_card.html" with dynamic=True %}
                <input type='hidden' name='{{widget.name}}' :value='musicbrainz_artist.mbid'>
            </div>
        </template>
    </div>

</div>

<script src='{% static "findshows/js/musicbrainz_artist_search_data.js" %}'></script>

app/findshows/templates/findshows/widgets/socials_links_widget.html
<table class="mt-2">
    <tr>
        <th class="font-light text-lg"> Display name </th>
        <th class="font-light text-lg w-full"> URL </th>
    </tr>
    {% for display_name, url in widget.socials_links %} {# num_links is included in data prep (fill w empty strings) #}
        <tr>
            <td> <input class="textinput" name="{{widget.name}}_display_name" type="text" value="{{ display_name }}"> </td>
            <td> <input class="textinput w-full" name="{{widget.name}}_url" type="text" value="{{ url }}"> </td>
        </tr>
    {% endfor %}
</table>

app/findshows/templates/findshows/widgets/styled_select.html
<div class="select-wrapper">
    <select name="{{ widget.name }}"{% include "django/forms/widgets/attrs.html" %}>{% for group_name, group_choices, group_index in widget.optgroups %}{% if group_name %}
        <optgroup label="{{ group_name }}">{% endif %}{% for option in group_choices %}
            {% include option.template_name with widget=option %}{% endfor %}{% if group_name %}
        </optgroup>{% endif %}{% endfor %}
    </select>
</div>

app/findshows/templates/findshows/widgets/venue_select.html
{% load static %}

<div class="flex items-center"
     x-data="venue_picker_data('{{widget.value|escapejs}}', '{{widget.venue.name|escapejs}}', {{widget.venue.is_verified|yesno:"true,false"}}, {{widget.venue.declined_listing|yesno:"true,false"}} )"
     x-cloak>

    <input type="hidden" name="{{widget.name}}" :value="selected_venue_id">

    <div class="grow p-2"
         x-ref="venue-search-plus-dropdown"
         @focusin="open_dropdown()"
         @click.outside="close_dropdown()"
    >
        <input class="textinput w-full" type="search"
               name="venue-search" placeholder="Select a venue..."
               x-model="search_text"
               hx-get="{% url 'findshows:venue_search_results' %}"
               hx-trigger="keyup changed delay:500ms"
               hx-target="#venue-search-results"
        >

        <ul id="venue-search-results"
            class="absolute popup-menu"
            x-show="show_search"
            @click="close_dropdown()"
            style="display: none;"
        >
        </ul>

        <div x-show="selected_venue_name && (!selected_venue_is_verified)" class="text-sm">
            This venue has not yet been verified; the show will be listed
            after verification is complete.
        </div>

        <div x-show="selected_venue_declined_listing" class="text-sm">
            This venue has declined to be listed on this website. This might
            be opted for by a DIY venue that has safety, capacity, or other
            concerns. Thanks for your understanding!
        </div>

    </div>

    <div class="w-32" @modal-form-success="on_venue_create">
        {% with title_text="New Venue" success_text="Venue created successfully!" form_html="findshows/htmx/venue_form.html" htmx_url="findshows:create_venue" %}
            {% include "findshows/partials/modal_form.html" %}
        {% endwith %}
    </div>

</div>

<script src='{% static "findshows/js/venue_picker_data.js" %}'></script>