app/findshows/urls.py
from functools import partial

from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "findshows"
urlpatterns = [
    path("", views.home, name="home"),
    path("user_settings", views.user_settings, name="user_settings"),
    path('about/', TemplateView.as_view(template_name='findshows/pages/about.html'), name="about"),
    path('artist_faq/', TemplateView.as_view(template_name='findshows/pages/artist_faq.html'), name="artist_faq"),
    path('contact/', views.contact, name="contact"),

    path("artist/<int:pk>", views.view_artist, name="view_artist"),
    path("artist/<int:pk>/edit", views.edit_artist, name="edit_artist"),
    path("artist_dashboard", views.artist_dashboard, name="artist_dashboard"),
    path("link_artist", views.link_artist, name="link_artist"),

    path("concert/<int:pk>", views.view_concert, name="view_concert"),
    path("concert/<int:pk>/edit", views.edit_concert, name="edit_concert"),
    path("concert/create", views.edit_concert, name="create_concert"),
    path("concert/<int:pk>/cancel", views.cancel_concert, name="cancel_concert"),
    path("concert/<int:pk>/uncancel", partial(views.cancel_concert, uncancel=True), name="uncancel_concert"),

    path("mod_dashboard", views.mod_dashboard, name="mod_dashboard"),
    path("htmx/mod_daily_digest", views.mod_daily_digest, name="mod_daily_digest"),
    path("htmx/mod_queue", views.mod_queue, name="mod_queue"),
    path("htmx/mod_outstanding_invites", views.mod_outstanding_invites, name="mod_outstanding_invites"),
    path("htmx/venue_verification/<int:pk>", views.venue_verification, name="venue_verification"),
    path("htmx/resend_invite/<int:pk>", views.resend_invite, name="resend_invite"),
    path("htmx/approve_artist_request/<int:pk>", views.approve_artist_request, name="approve_artist_request"),

    path("htmx/concert_search/", views.concert_search, name="concert_search"),

    path("htmx/mb_artist_search_results/", views.musicbrainz_artist_search_results, name="musicbrainz_artist_search_results"),
    path("htmx/venue_search_results/", views.venue_search_results, name="venue_search_results"),
    path("htmx/create_venue/", views.create_venue, name="create_venue"),
    path("htmx/create_temp_artist/", views.create_temp_artist, name="create_temp_artist"),
    path("htmx/request_artist_access/", views.request_artist_access, name="request_artist_access"),
    path("htmx/manage_artist_access/<int:pk>", views.manage_artist_access, name="manage_artist_access"),
    path("htmx/artist_search_results/", views.artist_search_results, name="artist_search_results"),
]

app/localmusic/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from findshows import views

urlpatterns = [
    path('', include("findshows.urls")),

    path('admin/', admin.site.urls),

    path("accounts/", include("django.contrib.auth.urls")),
    # accounts/login/ [name='login']
    # accounts/logout/ [name='logout']
    # accounts/password_change/ [name='password_change']
    # accounts/password_change/done/ [name='password_change_done']
    # accounts/password_reset/ [name='password_reset']
    # accounts/password_reset/done/ [name='password_reset_done']
    # accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
    # accounts/reset/done/ [name='password_reset_complete']
    path("accounts/create_account", views.create_account, name='create_account'),
    path("accounts/verify_email", views.verify_email, name='verify_email'),
    path("accounts/resend_email_verification", views.resend_email_verification, name='resend_email_verification'),

    path('captcha/', include("captcha.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/findshows/views.py
from datetime import timedelta
from operator import and_, or_
from functools import reduce
import json
from random import random, shuffle
from pymemcache.client.base import Client

from django.contrib.auth import login
from django.core.exceptions import PermissionDenied
from django.db import IntegrityError
from django.urls import reverse
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.postgres.search import TrigramSimilarity
from django.db.models import Q
from django.utils import timezone
from django.views.generic.dates import timezone_today
from django.conf import settings

from findshows.email import contact_email, invite_artist, invite_user_to_artist, send_artist_setup_info, send_verify_email
from findshows.widgets import ArtistAccessWidget

from .models import Artist, ArtistLinkingInfo, Concert, ConcertTags, EmailCodeError, EmailVerification, InviteDelayError, JPEGImageException, MusicBrainzArtist, Venue
from .forms import ArtistAccessForm, ArtistEditForm, ConcertForm, ContactForm, ModDailyDigestForm, RequestArtistForm, ShowFinderForm, TempArtistForm, UserCreationFormE, UserProfileForm, VenueForm


#################
## User Views ###
#################

def contact(request):
    success = False
    if request.POST:
        form = ContactForm(request.POST)

        if form.is_valid():
            memcache_client = Client(settings.MEMCACHE_LOCATION, timeout=3, connect_timeout=3)
            recent_contacts = memcache_client.incr('num_recent_contacts', 1)
            if recent_contacts is None:
                memcache_client.set('num_recent_contacts', 1, 60, True)
                recent_contacts = 1

            if recent_contacts > settings.MAX_CONTACTS_PER_MINUTE:
                form.add_error(None, "High contact volume; please try again in a minute. This is a spam prevention measure, thanks for understanding.")
            elif contact_email(form):
                success = True
                form = ContactForm()
    else:
        form = ContactForm()

    return render(request, "findshows/pages/contact.html", context={
        "form": form,
        "success": success
    })


@login_required
def user_settings(request):
    if request.POST:
        form = UserProfileForm(request.POST, instance=request.user.userprofile)
        if form.is_valid():
            form.save()
            return redirect('findshows:home')
    else:
        form = UserProfileForm(instance=request.user.userprofile)

    return render(request, "findshows/pages/user_settings.html", context={
        "form": form,
        "is_local_artist_account": is_local_artist_account(request.user)
    })


def create_account(request):
    if request.method != 'POST':
        user_form = UserCreationFormE()
        profile_form = UserProfileForm()
        next = request.GET.get('next')
    else:
        user_form = UserCreationFormE(request.POST)
        profile_form = UserProfileForm(request.POST)
        next = request.POST.get('next')

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()

            email_verification, invite_code = EmailVerification.create_and_get_invite_code(user.email)
            if not send_verify_email(email_verification, invite_code, profile_form):
                # Info about verification (failure or otherwise) will be shown
                # to the user in a banner on the home search page
                email_verification.delete()

            if "sendartistinfo" in request.POST:
                send_artist_setup_info(user.email)
            login(request, user)
            if next:
                return redirect(next)
            else:
                return redirect('findshows:home')

    context = {'user_form': user_form,
               'profile_form': profile_form,
               'next': next,
               }

    return render(request, 'registration/create_account.html', context)


@login_required
def verify_email(request):
    try:
        email_verification = EmailVerification.check_url(request.GET, request.user.email)
    except EmailCodeError as e:
        return render(request, "findshows/pages/email_verification.html",
                      {'error': e.message})

    request.user.userprofile.email_is_verified = True
    request.user.userprofile.save()
    email_verification.delete()

    return render(request, "findshows/pages/email_verification.html")


@login_required
def resend_email_verification(request):
    errorlist = []
    if request.user.userprofile.email_is_verified:
        errorlist.append("Email already verified.")
    else:
        try:
            email_verification = EmailVerification.objects.get(invited_email=request.user.email)
            invite_code = email_verification.regenerate_invite_code()
        except EmailVerification.DoesNotExist:
            email_verification, invite_code = EmailVerification.create_and_get_invite_code(request.user.email)

        if not send_verify_email(email_verification, invite_code, errorlist=errorlist):
            email_verification.delete()

    success = not errorlist

    return render(request, "findshows/htmx/email_verification_banner.html", {
        'success': success,
        'errorlist': errorlist,
    })

###################
## Artist Views ###
###################

def is_artist_account(user):
    return (not user.is_anonymous
            and len(user.userprofile.managed_artists.all()) > 0)


def is_local_artist_account(user):
    return (not user.is_anonymous
            and any(a.local for a in user.userprofile.managed_artists.all()) > 0)


def has_edit_privileges(user):
    return ((is_local_artist_account(user) and user.userprofile.email_is_verified) or
            is_mod(user))


@user_passes_test(is_artist_account)
def artist_dashboard(request):
    artists=request.user.userprofile.managed_artists.all()
    # Remove duplicates in case user manages multiple artists on same bill
    concerts = set(c for a in artists for c in a.concert_set.filter(date__gte=timezone_today()))
    concerts = sorted(concerts, key = lambda c: c.date)

    return render(request, "findshows/pages/artist_dashboard.html", context = {
        "artists": artists,
        "concerts": concerts,
        "is_local_artist": is_local_artist_account(request.user)
    })


def view_artist(request, pk):
    artist = get_object_or_404(Artist, pk=pk)
    can_edit = (not request.user.is_anonymous
                and artist in request.user.userprofile.managed_artists.all())

    if artist.is_temp_artist and not can_edit:
        raise PermissionDenied

    upcoming_concerts = Concert.objects.all() if can_edit else Concert.publically_visible()
    upcoming_concerts = upcoming_concerts.filter(date__gte=timezone.now(), artists=artist)

    return render(request, "findshows/pages/view_artist.html", context={
        'artist': artist,
        'can_edit': can_edit,
        'upcoming_concerts': upcoming_concerts
    })


@login_required
def edit_artist(request, pk):
    artist = get_object_or_404(Artist, pk=pk)
    if artist not in request.user.userprofile.managed_artists.all():
        raise PermissionDenied

    if request.method != 'POST':
        form = ArtistEditForm(instance=artist)
    else:
        form = ArtistEditForm(request.POST, request.FILES, instance=artist)
        if form.is_valid():
            try:
                form.save()
                return redirect(reverse('findshows:view_artist', args=[pk]))
            except JPEGImageException as e:
                form.add_error('profile_picture', e.message)

    context = {'form': form,
               'pk': pk,
               'is_temp_artist': artist.is_temp_artist}

    return render(request, 'findshows/pages/edit_artist.html', context)


def artist_search_results(request):
    if not (request.GET and request.GET["artist-search"] and request.GET["idx"]):
        return HttpResponse("")

    keywords = request.GET["artist-search"].split()
    idx = int(request.GET["idx"])

    search_results = Artist.objects.filter(
        reduce(and_, (Q(name__icontains=k) for k in keywords))
    )[:5]
    return render(request, "findshows/htmx/artist_search_results.html", {
        "artists": search_results,
        "idx": idx
    })


def has_exceeded_daily_invites(user):
    return (not is_mod(user) and
            records_created_today(ArtistLinkingInfo, user.userprofile) >= settings.MAX_DAILY_INVITES)

def is_new_artist_account(user):
    if is_mod(user):
        return False
    return (not user.userprofile.given_artist_access_datetime or
            user.userprofile.given_artist_access_datetime > timezone.now() - timedelta(settings.INVITE_BUFFER_DAYS))

def create_temp_artist(request):
    if not (has_edit_privileges(request.user)):
        return render(request, 'findshows/htmx/cant_create_artist.html', {
            'no_privileges': True
        })

    if has_exceeded_daily_invites(request.user):
        return render(request, 'findshows/htmx/cant_create_artist.html')

    if is_new_artist_account(request.user):
        return render(request, 'findshows/htmx/cant_create_artist.html', context={'new_account_delay': settings.INVITE_BUFFER_DAYS})

    # The latter condition is a slightly hacky way of telling whether this HTMX
    # request is being triggered by page load (we should provide blank form) or
    # click (we should process form and display errors if they exist)
    if request.POST and 'temp_artist-name' in request.POST:
        form = TempArtistForm(request.POST)
    else:
        form = TempArtistForm()

    valid = form.is_valid()
    if valid:
        artist = form.save(commit=False)
        artist.created_by = request.user.userprofile
        artist.save()

app/findshows/templates/findshows/pages/about.html
{% extends "localmusic/base.html" %}
{% load findshows_tags %}
{% block content %}
<div class="p-3">
    <h1> About </h1>

    <div class="fieldgroup">
        <h2> {% custom_text 'ST' %} </h2>
        <p class="m-4">
            {% custom_text 'AB' %}
        </p>
    </div>

    <div class="fieldgroup mt-6">
        <h2> The localmusic project </h2>
        <p class="m-4">
            This website is an instance of the
            <a class="link" target="_blank"
               href="https://github.com/ruebeckscube/localmusic">
                localmusic
            </a>
            project. We aim to make local music more discoverable and accessible,
            with minimal demands on your attention (one email a week! or on-demand on the website)
            and minimal dependence on the big social media platforms. You can discover shows on your
            own by sampling artists' music with one click, or use our recommendation
            system (always optional and user-controlled) powered by the open-source
            <a class="link" target="_blank"
               href="https://musicbrainz.org/">
                MusicBrainz
            </a>
            database.
        </p>
        <p class="m-4">
            Artists post their own shows and create their own profiles&mdash;if you're an artist
            looking to list your shows, request access via your
            <a class="link"
               href="{% url 'findshows:user_settings' %}">
                settings
            </a>
            page!
        </p>
        <p class="m-4">
            The project is free as in freedom, free as in beer for self-hosting, and open-source.
            Visit the
            <a class="link" target="_blank"
               href="https://github.com/ruebeckscube/localmusic">
                setup guide
            </a>
            for more information and instructions on setting up an instance for your city.
        </p>
    </div>
</div>
{% endblock %}

app/findshows/templates/findshows/pages/artist_dashboard.html
{% extends "localmusic/base.html" %}

{% block content %}
<div class="p-3">
    <h1>Artist Dashboard</h1>
    <div class="flex flex-wrap">
        {% if is_local_artist %}
            <div class="bg-highlight-item-light/40 p-3 m-3 min-w-80 flex-grow">
                <h2> Actions </h2>
                <div class="mx-auto w-72">
                    <a class="btn block w-full" href="{% url 'findshows:create_concert' %}">
                        Create new show listing
                    </a>
                </div>
                
                <div class="mx-auto w-72">
                    <form>
                        {% csrf_token %}
                        {% with title_text="Invite Artist" success_text="Invite sent successfully!" form_html="findshows/htmx/temp_artist_form.html" htmx_url="findshows:create_temp_artist" %}
                            {% include "findshows/partials/modal_form.html" %}
                        {% endwith %}
                    </form>
                </div>
            </div>
        {% endif %}

        <div class="bg-highlight-item-light/40 p-3 m-3 min-w-70 flex-grow">
            <h2> Useful links </h2>
            <div class="pl-3">
                <a class="link" target="_blank" href="{% url 'findshows:artist_faq' %}">Artist FAQ</a>
            </div>
        </div>
    </div>

    
    <div class="bg-highlight-item-light/40 p-3 m-3">
        <h2>Artist pages</h2>
        
        <div class="flex flex-wrap align-middle items-center justify-center">
            {% for artist in artists %}
            <div class="flex flex-col items-center m-5 bg-sub-background p-4">
                <div class="text-lg">
                    {{artist.name}}
                </div>
                <div class="w-60 h-60 m-2 flex justify-center items-center">
                    {% if artist.profile_picture %}
                    <img class="max-h-60 max-w-60 object-contain" src="{{ artist.profile_picture.url }}">
                    {% else %}
                    <p class="text-red-700">
                        This artist profile is incomplete! Please edit it so your shows can be listed publically.
                    </p>
                    {% endif %}
                </div>
                <div class="flex justify-center flex-wrap">
                    <a class="btn block" href="{% url 'findshows:view_artist' artist.pk %}">View</a>
                    <a class="btn block" href="{% url 'findshows:edit_artist' artist.pk %}">Edit</a>
                    <form class="mx-auto">
                        {% csrf_token %}
                        {% with title_text="Manage access" success_text="Artist access saved!" form_html="findshows/htmx/artist_access_form.html" htmx_url="findshows:manage_artist_access" htmx_param=artist.pk %}
                            {% include "findshows/partials/modal_form.html"%}
                        {% endwith %}
                    </form>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    
    <div class="bg-highlight-item-light/40 p-3 m-3">
        <h2> My Shows </h2>
        
        <div class="flex flex-col w-full align-middle">
            {% for concert in concerts %}
            <div class="flex max-sm:flex-col m-2">
                <div class="w-full">
                    {% include "findshows/partials/concert_card.html" %}
                </div>
                {% if concert.created_by == user.userprofile %}
                <div class="w-60 flex sm:flex-col justify-center items-center mx-auto my-2">
                    <a class="btn" href="{% url 'findshows:edit_concert' concert.pk %}"> Edit </a>
                    {% include "findshows/htmx/cancel_concert_button.html" %}
                </div>
                {% endif %}
            </div>
            {% empty %}
            <div class="w-fit mx-auto p-2"> You do not have any upcoming shows listed. </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

app/findshows/templates/findshows/pages/artist_faq.html
{% extends "localmusic/base.html" %}
{% load findshows_tags %}

{% block content %}
<div class="p-3"
     x-data="{selected_title: ''}"
>
    <h1> Artist FAQ </h1>

    <h2 class="ml-2"> How do I&hellip; </h2>

    <div class="mx-4">
        {% accordion_element title="&hellip;create an artist profile/get access to post shows?" %}
        There are two ways to get artist access! If you know somebody who already has artist access, they
        can invite you via their Settings page (or via the concert creation page if
        you have a show coming up together). If not, go to your
        <a class="link" href="{% url 'findshows:user_settings' %}">Settings</a> page
        and click <em>Request Artist Access</em>. You will need to provide your artist
        name, as well as a website or social media account where we can contact
        you to verify your identity. A mod will review the request and reach out
        as soon as possible.
        {% endaccordion_element %}

        {% accordion_element title="&hellip;post a show?" %}
        Log in; from the menu, go to your
        <a class="link" href="{% url 'findshows:artist_dashboard' %}">artist dashboard</a>
        and click <em>Create new show listing</em>.
        {% endaccordion_element %}

        {% accordion_element title="&hellip;edit a show I'm a part of?" %}
        Only the user who initially created a show can edit it. Log in; from the menu, go to your
        <a class="link" href="{% url 'findshows:artist_dashboard' %}">artist dashboard</a>.
        If you created a show, it should have an <em>Edit</em> button next to it. If
        you just want to edit your artist info it appears on the concert listing,
        you can do that by editing your artist profile (also from the dashboard).
        {% endaccordion_element %}

        {% accordion_element title="&hellip;delete/cancel a show I'm a part of?" %}
        Only the user who initially created a show can cancel it. Log in; from the menu, go to your
        <a class="link" href="{% url 'findshows:artist_dashboard' %}">artist dashboard</a>.
        If you created a show, it should have a <em>Cancel</em> button next to it. The concert's
        detail page will now display prominently the fact that it is cancelled, and it will no
        longer show up anywhere else (search, artist pages, emails). You cannot delete a show.
        {% endaccordion_element %}
        
        {% accordion_element title="&hellip;give a bandmate/manager access to list shows?" %}
        Multiple users can manage the same artist. Log in; from the menu, go to your
        <a class="link" href="{% url 'findshows:artist_dashboard' %}">artist dashboard</a>.
        Click <em>Manage access</em> under the relevant artist, enter the email of the person to whom you'd like to
        give access, click <em>Add</em>, then <em>Submit</em>.
        {% endaccordion_element %}    
    </div>

</div>
{% endblock %}

app/findshows/templates/findshows/pages/edit_concert.html
{% extends "localmusic/base.html" %}

{% block content %}
    <h1 class="pl-3 mb-1"> Edit Concert </h1>
    <form method="post"
          enctype="multipart/form-data"
          {% if pk %}
          action="{% url 'findshows:edit_concert' pk %}"
          {% else %}
          action="{% url 'findshows:create_concert' %}"
          {% endif %}
    >
        {% csrf_token %}
        <div>
            {{ form.non_field_errors }}
        </div>
        <div class="flex max-md:flex-col w-full h-full">
            <div class="md:w-1/2 flex flex-col">
                <div class="flex flex-col fieldgroup">
                    {{ form.poster.as_field_group }}
                </div>
                <div class="flex flex-col fieldgroup">
                    {{ form.bill.as_field_group }}
                </div>
                <div class="flex max-xl:flex-col">
                    <div class="flex flex-col fieldgroup xl:w-3/4">
                        {{ form.venue.as_field_group }}
                    </div>
                    <div class="flex flex-col fieldgroup xl:w-1/4">
                        {{ form.ages.as_field_group }}
                    </div>
                </div>
            </div>
            <div class="md:w-1/2 flex flex-col">
                <div class="flex flex-col fieldgroup">
                    {{ form.date.as_field_group }}
                </div>
                <div class="flex max-xs:flex-col">
                    <div class="flex flex-col fieldgroup grow">
                        {{ form.doors_time.as_field_group }}
                    </div>
                    <div class="flex flex-col fieldgroup grow">
                        {{ form.start_time.as_field_group }}
                    </div>
                    <div class="flex flex-col fieldgroup grow">
                        {{ form.end_time.as_field_group }}
                    </div>
                </div>
                <div class="flex flex-col fieldgroup">
                    {{ form.ticket_link.as_field_group }}
                </div>
                <div class="flex flex-col fieldgroup">
                    {{ form.ticket_description.as_field_group }}
                </div>
                <div class="flex flex-col fieldgroup">
                    {{ form.description.as_field_group }}
                </div>
                <div class="flex flex-col fieldgroup">
                    {{ form.tags.as_field_group }}
                </div>
                <div>
                    <input class="block btn w-full max-w-30 m-8 mx-auto" type="submit" value="Save">
                </div>
            </div>
        </div>
    </form>
{% endblock %}

app/findshows/templates/findshows/pages/mod_dashboard.html
{% extends "localmusic/base.html" %}

{% block content %}
    <div class="p-3">
        <h1> Mod Dashboard </h1>

        <div x-data="{selectedTab: '{{ date|yesno:'dailyDigest,actionRequired'}}'}"
            class="flex flex-wrap max-w-4xl fieldgroup items-center">

            <button type="button" class="btn"
                    @mouseup="selectedTab='actionRequired'"
                    :class="selectedTab==='actionRequired' ? 'bg-highlight-item-light border-4 border-clickable font-semibold text-black shadow-none' : 'shadow-2xl border-transparent' "
                    hx-get="{% url 'findshows:mod_queue' %}"
                    {% if date %}
                    hx-trigger="click"
                    {% else %}
                    hx-trigger="click,load"
                    {% endif %}
                    hx-target="#mod-content"
                    hx-swap="innerHTML">
                Action required
            </button>

            <button type="button" class="btn"
                    @mouseup="selectedTab='dailyDigest'"
                    :class="selectedTab==='dailyDigest' ? 'bg-highlight-item-light border-4 border-clickable font-semibold text-black shadow-none' : 'shadow-2xl border-transparent' "
                    hx-get="{% url 'findshows:mod_daily_digest' %}"
                    {% if date %}
                    hx-trigger="click,load"
                    hx-vals='{"date": "{{date}}"}'
                    {% else %}
                    hx-trigger="click"
                    {% endif %}
                    hx-trigger="click"
                    hx-target="#mod-content"
                    hx-swap="innerHTML">
                Daily digest
            </button>

            <button type="button" class="btn"
                    @mouseup="selectedTab='outstandingInvites'"
                    :class="selectedTab==='outstandingInvites' ? 'bg-highlight-item-light border-4 border-clickable font-semibold text-black shadow-none' : 'shadow-2xl border-transparent' "
                    hx-get="{% url 'findshows:mod_outstanding_invites' %}"
                    hx-trigger="click"
                    hx-target="#mod-content"
                    hx-swap="innerHTML">
                Outstanding invites
            </button>

            <div class="basis-0 grow"></div>

            <form>
                {% csrf_token %}
                {% with title_text="Invite Artist" success_text="Invite sent successfully!" form_html="findshows/htmx/temp_artist_form.html" htmx_url="findshows:create_temp_artist" %}
                    {% include "findshows/partials/modal_form.html" %}
                {% endwith %}
            </form>


        </div>

        <div class="p-3" id="mod-content"></div>

    </div>

{% endblock %}

app/findshows/templates/findshows/pages/view_artist.html
{% extends "localmusic/base.html" %}
{% load findshows_tags %}

{% block content %}
    {% if can_edit %}
        <div class="flex justify-center mx-auto w-fit">
            <a class="block btn w-30 m-2" href={% url "findshows:edit_artist" artist.pk %}> Edit </a>
            <a class="block btn w-60 m-2" href={% url "findshows:artist_dashboard" %}> Artist dashboard </a>
        </div>
    {% endif %}
    <div class="flex max-md:flex-col w-full">
        {# Name and socials #}
        <div class="md:w-3/5 m-2 flex flex-col content-center justify-around bg-sub-background">
                <h1 class="text-[10vw] md:text-[8vw] text-center font-extralight mt-8 md:my-auto">
                    {{artist.name}}
                </h1>

                <div class="flex flex-row w-fit mx-auto self-end">
                    {% for link in artist.socials_links %}
                        <a class="link text-lg mx-4 my-3 md:my-8" href="{{link.1}}" target="_blank">{{link.0}}</a>
                    {% endfor %}
                </div>
        </div>
        {# Profile pic #}
        <div class="md:w-2/5">
            <div class="bg-sub-background m-2">
                {% if artist.profile_picture %}
                    <img class="w-full max-h-[30em] object-contain"
                         src="{{ artist.profile_picture.url }}">
                {% endif %}
            </div>
        </div>
    </div>
    <div class="flex max-md:flex-col w-full">
        {# Preview players #}
        <div class="m-2 p-3 md:w-1/3 flex flex-col justify-around align-middle items-center bg-sub-background">
            {% preview_player artist %}
        </div>
        {# Bio and similar artists #}
        <div class="md:w-2/3 m-2 bg-sub-background">
            <p class="p-10 w-full max-w-[50em] mx-auto text-justify">
                {{artist.bio}}
            </p>
            <div class="flex flex-wrap justify-center items-center pb-4">
                <p> Sounds like: </p>
                {% for musicbrainz_artist in artist.similar_musicbrainz_artists.all %}
                    {% include "../partials/musicbrainz_card.html" %}
                {% endfor %}
            </div>
        </div>
    </div>

    {# Youtube #}
    <div class="flex max-md:flex-col justify-center items-center ">
        {% for youtube_id in artist.youtube_ids %}
            <iframe type="text/html" width="640" height="360"
                    class="w-full md:max-w-1/2 m-2 bg-sub-background p-2"
                    src="https://www.youtube.com/embed/{{ youtube_id }}?autoplay=0&origin=http://example.com"
                    allowfullscreen
                    referrerpolicy="strict-origin-when-cross-origin"
                    frameborder="0"></iframe>
        {% endfor %}
    </div>

    {# Upcoming shows #}
    <div class="w-full">
        <h2 class="text-center w-2/3 min-w-30 my-4 p-2 mx-auto bg-sub-background"> Upcoming shows</h2>
        {% for concert in upcoming_concerts %}
            {% include "../partials/concert_card.html" %}
        {% empty %}
            <p class="text-center w-full">No upcoming shows listed!</p>
        {% endfor %}
    </div>
{% endblock %}