app/findshows/urls.py
from functools import partial

from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "findshows"
urlpatterns = [
    path("", views.home, name="home"),
    path("user_settings", views.user_settings, name="user_settings"),
    path('about/', TemplateView.as_view(template_name='findshows/pages/about.html'), name="about"),
    path('artist_faq/', TemplateView.as_view(template_name='findshows/pages/artist_faq.html'), name="artist_faq"),
    path('contact/', views.contact, name="contact"),

    path("artist/<int:pk>", views.view_artist, name="view_artist"),
    path("artist/<int:pk>/edit", views.edit_artist, name="edit_artist"),
    path("artist_dashboard", views.artist_dashboard, name="artist_dashboard"),
    path("link_artist", views.link_artist, name="link_artist"),

    path("concert/<int:pk>", views.view_concert, name="view_concert"),
    path("concert/<int:pk>/edit", views.edit_concert, name="edit_concert"),
    path("concert/create", views.edit_concert, name="create_concert"),
    path("concert/<int:pk>/cancel", views.cancel_concert, name="cancel_concert"),
    path("concert/<int:pk>/uncancel", partial(views.cancel_concert, uncancel=True), name="uncancel_concert"),

    path("mod_dashboard", views.mod_dashboard, name="mod_dashboard"),
    path("htmx/mod_daily_digest", views.mod_daily_digest, name="mod_daily_digest"),
    path("htmx/mod_queue", views.mod_queue, name="mod_queue"),
    path("htmx/mod_outstanding_invites", views.mod_outstanding_invites, name="mod_outstanding_invites"),
    path("htmx/venue_verification/<int:pk>", views.venue_verification, name="venue_verification"),
    path("htmx/resend_invite/<int:pk>", views.resend_invite, name="resend_invite"),
    path("htmx/approve_artist_request/<int:pk>", views.approve_artist_request, name="approve_artist_request"),

    path("htmx/concert_search/", views.concert_search, name="concert_search"),

    path("htmx/mb_artist_search_results/", views.musicbrainz_artist_search_results, name="musicbrainz_artist_search_results"),
    path("htmx/venue_search_results/", views.venue_search_results, name="venue_search_results"),
    path("htmx/create_venue/", views.create_venue, name="create_venue"),
    path("htmx/create_temp_artist/", views.create_temp_artist, name="create_temp_artist"),
    path("htmx/request_artist_access/", views.request_artist_access, name="request_artist_access"),
    path("htmx/manage_artist_access/<int:pk>", views.manage_artist_access, name="manage_artist_access"),
    path("htmx/artist_search_results/", views.artist_search_results, name="artist_search_results"),
]

app/localmusic/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from findshows import views

urlpatterns = [
    path('', include("findshows.urls")),

    path('admin/', admin.site.urls),

    path("accounts/", include("django.contrib.auth.urls")),
    # accounts/login/ [name='login']
    # accounts/logout/ [name='logout']
    # accounts/password_change/ [name='password_change']
    # accounts/password_change/done/ [name='password_change_done']
    # accounts/password_reset/ [name='password_reset']
    # accounts/password_reset/done/ [name='password_reset_done']
    # accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
    # accounts/reset/done/ [name='password_reset_complete']
    path("accounts/create_account", views.create_account, name='create_account'),
    path("accounts/verify_email", views.verify_email, name='verify_email'),
    path("accounts/resend_email_verification", views.resend_email_verification, name='resend_email_verification'),

    path('captcha/', include("captcha.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/findshows/views.py
from datetime import timedelta
from operator import and_, or_
from functools import reduce
import json
from random import random, shuffle
from pymemcache.client.base import Client

from django.contrib.auth import login
from django.core.exceptions import PermissionDenied
from django.db import IntegrityError
from django.urls import reverse
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.postgres.search import TrigramSimilarity
from django.db.models import Q
from django.utils import timezone
from django.views.generic.dates import timezone_today
from django.conf import settings

from findshows.email import contact_email, invite_artist, invite_user_to_artist, send_artist_setup_info, send_verify_email
from findshows.widgets import ArtistAccessWidget

from .models import Artist, ArtistLinkingInfo, Concert, ConcertTags, EmailCodeError, EmailVerification, InviteDelayError, JPEGImageException, MusicBrainzArtist, Venue
from .forms import ArtistAccessForm, ArtistEditForm, ConcertForm, ContactForm, ModDailyDigestForm, RequestArtistForm, ShowFinderForm, TempArtistForm, UserCreationFormE, UserProfileForm, VenueForm


#################
## User Views ###
#################

def contact(request):
    success = False
    if request.POST:
        form = ContactForm(request.POST)

        if form.is_valid():
            memcache_client = Client(settings.MEMCACHE_LOCATION, timeout=3, connect_timeout=3)
            recent_contacts = memcache_client.incr('num_recent_contacts', 1)
            if recent_contacts is None:
                memcache_client.set('num_recent_contacts', 1, 60, True)
                recent_contacts = 1

            if recent_contacts > settings.MAX_CONTACTS_PER_MINUTE:
                form.add_error(None, "High contact volume; please try again in a minute. This is a spam prevention measure, thanks for understanding.")
            elif contact_email(form):
                success = True
                form = ContactForm()
    else:
        form = ContactForm()

    return render(request, "findshows/pages/contact.html", context={
        "form": form,
        "success": success
    })


@login_required
def user_settings(request):
    if request.POST:
        form = UserProfileForm(request.POST, instance=request.user.userprofile)
        if form.is_valid():
            form.save()
            return redirect('findshows:home')
    else:
        form = UserProfileForm(instance=request.user.userprofile)

    return render(request, "findshows/pages/user_settings.html", context={
        "form": form,
        "is_local_artist_account": is_local_artist_account(request.user)
    })


def create_account(request):
    if request.method != 'POST':
        user_form = UserCreationFormE()
        profile_form = UserProfileForm()
        next = request.GET.get('next')
    else:
        user_form = UserCreationFormE(request.POST)
        profile_form = UserProfileForm(request.POST)
        next = request.POST.get('next')

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()

            email_verification, invite_code = EmailVerification.create_and_get_invite_code(user.email)
            if not send_verify_email(email_verification, invite_code, profile_form):
                # Info about verification (failure or otherwise) will be shown
                # to the user in a banner on the home search page
                email_verification.delete()

            if "sendartistinfo" in request.POST:
                send_artist_setup_info(user.email)
            login(request, user)
            if next:
                return redirect(next)
            else:
                return redirect('findshows:home')

    context = {'user_form': user_form,
               'profile_form': profile_form,
               'next': next,
               }

    return render(request, 'registration/create_account.html', context)


@login_required
def verify_email(request):
    try:
        email_verification = EmailVerification.check_url(request.GET, request.user.email)
    except EmailCodeError as e:
        return render(request, "findshows/pages/email_verification.html",
                      {'error': e.message})

    request.user.userprofile.email_is_verified = True
    request.user.userprofile.save()
    email_verification.delete()

    return render(request, "findshows/pages/email_verification.html")


@login_required
def resend_email_verification(request):
    errorlist = []
    if request.user.userprofile.email_is_verified:
        errorlist.append("Email already verified.")
    else:
        try:
            email_verification = EmailVerification.objects.get(invited_email=request.user.email)
            invite_code = email_verification.regenerate_invite_code()
        except EmailVerification.DoesNotExist:
            email_verification, invite_code = EmailVerification.create_and_get_invite_code(request.user.email)

        if not send_verify_email(email_verification, invite_code, errorlist=errorlist):
            email_verification.delete()

    success = not errorlist

    return render(request, "findshows/htmx/email_verification_banner.html", {
        'success': success,
        'errorlist': errorlist,
    })

###################
## Artist Views ###
###################

def is_artist_account(user):
    return (not user.is_anonymous
            and len(user.userprofile.managed_artists.all()) > 0)


def is_local_artist_account(user):
    return (not user.is_anonymous
            and any(a.local for a in user.userprofile.managed_artists.all()) > 0)


def has_edit_privileges(user):
    return ((is_local_artist_account(user) and user.userprofile.email_is_verified) or
            is_mod(user))


@user_passes_test(is_artist_account)
def artist_dashboard(request):
    artists=request.user.userprofile.managed_artists.all()
    # Remove duplicates in case user manages multiple artists on same bill
    concerts = set(c for a in artists for c in a.concert_set.filter(date__gte=timezone_today()))
    concerts = sorted(concerts, key = lambda c: c.date)

    return render(request, "findshows/pages/artist_dashboard.html", context = {
        "artists": artists,
        "concerts": concerts,
        "is_local_artist": is_local_artist_account(request.user)
    })


def view_artist(request, pk):
    artist = get_object_or_404(Artist, pk=pk)
    can_edit = (not request.user.is_anonymous
                and artist in request.user.userprofile.managed_artists.all())

    if artist.is_temp_artist and not can_edit:
        raise PermissionDenied

    upcoming_concerts = Concert.objects.all() if can_edit else Concert.publically_visible()
    upcoming_concerts = upcoming_concerts.filter(date__gte=timezone.now(), artists=artist)

    return render(request, "findshows/pages/view_artist.html", context={
        'artist': artist,
        'can_edit': can_edit,
        'upcoming_concerts': upcoming_concerts
    })


@login_required
def edit_artist(request, pk):
    artist = get_object_or_404(Artist, pk=pk)
    if artist not in request.user.userprofile.managed_artists.all():
        raise PermissionDenied

    if request.method != 'POST':
        form = ArtistEditForm(instance=artist)
    else:
        form = ArtistEditForm(request.POST, request.FILES, instance=artist)
        if form.is_valid():
            try:
                form.save()
                return redirect(reverse('findshows:view_artist', args=[pk]))
            except JPEGImageException as e:
                form.add_error('profile_picture', e.message)

    context = {'form': form,
               'pk': pk,
               'is_temp_artist': artist.is_temp_artist}

    return render(request, 'findshows/pages/edit_artist.html', context)


def artist_search_results(request):
    if not (request.GET and request.GET["artist-search"] and request.GET["idx"]):
        return HttpResponse("")

    keywords = request.GET["artist-search"].split()
    idx = int(request.GET["idx"])

    search_results = Artist.objects.filter(
        reduce(and_, (Q(name__icontains=k) for k in keywords))
    )[:5]
    return render(request, "findshows/htmx/artist_search_results.html", {
        "artists": search_results,
        "idx": idx
    })


def has_exceeded_daily_invites(user):
    return (not is_mod(user) and
            records_created_today(ArtistLinkingInfo, user.userprofile) >= settings.MAX_DAILY_INVITES)

def is_new_artist_account(user):
    if is_mod(user):
        return False
    return (not user.userprofile.given_artist_access_datetime or
            user.userprofile.given_artist_access_datetime > timezone.now() - timedelta(settings.INVITE_BUFFER_DAYS))

def create_temp_artist(request):
    if not (has_edit_privileges(request.user)):
        return render(request, 'findshows/htmx/cant_create_artist.html', {
            'no_privileges': True
        })

    if has_exceeded_daily_invites(request.user):
        return render(request, 'findshows/htmx/cant_create_artist.html')

    if is_new_artist_account(request.user):
        return render(request, 'findshows/htmx/cant_create_artist.html', context={'new_account_delay': settings.INVITE_BUFFER_DAYS})

    # The latter condition is a slightly hacky way of telling whether this HTMX
    # request is being triggered by page load (we should provide blank form) or
    # click (we should process form and display errors if they exist)
    if request.POST and 'temp_artist-name' in request.POST:
        form = TempArtistForm(request.POST)
    else:
        form = TempArtistForm()

    valid = form.is_valid()
    if valid:
        artist = form.save(commit=False)
        artist.created_by = request.user.userprofile
        artist.save()

app/findshows/templates/findshows/htmx/artist_access_form.html
{% if partial_errors %}
    {{ partial_errors }}
{% endif %}

{{ artist_access_form.non_field_errors }}

<div class="fieldgroup">
    {{ artist_access_form.users.errors }}
    {{ artist_access_form.users }}
</div>

<div class="helptext my-3">
    Changes are not saved until you press submit. Make sure you trust anyone
    that you're giving access to; they can post shows from this artist or even
    remove you from accessing it!
</div>

app/findshows/templates/findshows/htmx/artist_search_results.html
{% for artist in artists %}
    <li class="menuitem hover:text-clickable-h"
        @click="select_artist({{idx|escapejs}}, '{{artist.name|escapejs}}', '{{artist.id|escapejs}}')">
        {{artist.name}}
    </li>
{% endfor %}

app/findshows/templates/findshows/htmx/cant_create_artist.html
<div class="text-center m-auto fieldgroup">
    {% if new_account_delay %}
        Users newly given artist access must wait {{  new_account_delay }} days
        before inviting other users.
    {% elif no_privileges %}
        You must have a local artist account with a verified email to
        invite an artist to the platform.
    {% else %}
        You've hit the daily limit for inviting artists&mdash;please
        try again in 24 hours or contact an admin if it's urgent.
    {% endif %}
</div>

app/findshows/templates/findshows/htmx/cant_create_venue.html
<div class="text-center m-auto fieldgroup">
    You've hit the daily limit for creating venues&mdash;please
    try again in 24 hours or contact an admin if it's urgent.
</div>

app/findshows/templates/findshows/htmx/cant_request_artist.html
<div class="text-center m-auto fieldgroup">
    {% if not user.userprofile.email_is_verified %}
        You must verify your email before requesting artist access.
    {% else %}
        You've already submitted an artist request; please wait for a response from
        moderators. Once you've been granted access you can add additional artists
        without mod approval.
    {% endif %}
</div>

app/findshows/templates/findshows/htmx/mod_artist_buttons.html
<div class="mod-artist-buttons flex flex-col">
    {% if success %}
        Request approved successfully!
    {% elif artist.is_active_request %}
        {% if errors %}
            {{ errors }}
        {% endif %}
        <form type="post">
            {% csrf_token %}
            <input class="btn"
                   type="button"
                   name="approve-request"
                   hx-post="{% url 'findshows:approve_artist_request' artist.id %}"
                   hx-trigger="click"
                   value="Approve request"
                   hx-target="closest .mod-artist-buttons"
                   hx-swap="outerHTML"
            >
    {% elif artist.artistlinkinginfo_set.all %}
        {% for ali in artist.artistlinkinginfo_set.all %}
            {% include "findshows/htmx/mod_resend_invite_button.html" %}
        {% endfor %}
    {% elif artist.is_temp_artist %}
        Artist linked; profile incomplete
    {% else %}
        Artist linked & profile complete
    {% endif %}
</div>

app/findshows/templates/findshows/htmx/mod_daily_digest.html
<div hx-get="{% url 'findshows:mod_daily_digest' %}"
     hx-trigger="widget-update from:body delay:.1s"
     hx-include="#mod-digest-form"
     hx-target="this"
>
    <div class="text-lg"> Review records created on a given date.</div>
    <form class="flex" method="GET" action="" id="mod-digest-form">
        {% for field in form %}
            <div class="fieldgroup">
                {{ field.as_field_group }}
            </div>
        {% endfor %}
    </form>

    <h2 class="my-4"> Artists </h2>
    {% include "findshows/partials/mod_artist_table.html" with empty_message="No artists created on this date." %}

    <h2 class="my-4"> Venues </h2>
    {% include "findshows/partials/mod_venue_table.html" with empty_message="No venues created on this date." %}

    <h2 class="my-4"> Concerts </h2>
    {% for concert in concerts %}
        <div class="flex items-center">
            {% include "findshows/partials/concert_card.html" %}
            {% if is_admin %}
                <a class="link w-30" href="{% url 'admin:findshows_concert_change' concert.pk %}">Admin edit</a>
            {% endif %}
        </div>
    {% empty %}
        <div class="ml-3">
            No concerts created on this date.
        </div>
    {% endfor %}
</div>

app/findshows/templates/findshows/htmx/mod_outstanding_invites.html
<div>
    <div class="text-lg"> Reveiw outstanding invites. </div>
    <h2 class="my-4"> Invites </h2>
    {% if artist_linking_infos %}
        <table class="w-full text-center max-w-5xl fieldgroup p-5">
            <tr class="bg-highlight-item-light text-lg">
                <th> Artist name </th>
                <th> Website </th>
                <th> Email </th>
                <th> Actions </th>
                {% if is_admin %}
                    <th> Admin </th>
                {% endif %}
            </tr>

            {% for ali in artist_linking_infos %}
                <tr class="odd:bg-white">
                    <td>
                        {{ ali.artist }}
                    </td>
                    <td>
                        {% if ali.artist.socials_links %}
                            {% for link in ali.artist.socials_links %}
                                <a class="link" href="{{link.1}}" target="_blank">{{link.0}}</a>
                            {% endfor %}
                        {% endif %}
                    </td>
                    <td>
                        <a class="link" href="mailto:{{ ali.invited_email }}">{{ ali.invited_email }}</a>
                    </td>
                    <td>
                        {% include "findshows/htmx/mod_resend_invite_button.html" %}
                    </td>
                    {% if is_admin %}
                        <td>
                            <a class="link" href="{% url 'admin:findshows_artistlinkinginfo_change' ali.pk %}">Admin edit</a>
                        </td>
                    {% endif %}
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <div class="ml-3">
            No outstanding invites.
        </div>
    {% endif %}
</div>

app/findshows/templates/findshows/htmx/mod_resend_invite_button.html
<div class="mod-invite-button flex flex-col items-center">
    {% if success %}
        Invite successfully sent!
    {% else %}
        <form type="post">
            {% csrf_token %}
            <input class="btn"
                   type="button"
                   name="resend-invite"
                   hx-post="{% url 'findshows:resend_invite' ali.id %}"
                   hx-trigger="click"
                   value="Resend invite"
                   hx-target="closest .mod-invite-button"
                   hx-swap="outerHTML"
            >
        </form>
        {% if errors %}
            <div class="errorlist max-w-sm">
                {{ errors }}
            </div>
        {% endif %}
    {% endif %}
</div>

app/findshows/templates/findshows/htmx/musicbrainz_artist_search_results.html
{% for mb_artist in musicbrainz_artists %}
    <li class="menuitem hover:text-clickable-h"
        @click="add_artist('{{mb_artist.mbid|escapejs}}', '{{mb_artist.name|escapejs}}')"
    >
        {{  mb_artist.name }}
        {% if mb_artist.disambiguation %}
            <span class="text-gray-500"> ({{ mb_artist.disambiguation }}) </span>
        {% endif %}
    </li>
{% endfor %}

app/findshows/templates/findshows/htmx/request_artist_form.html
<p class="text-xs">
    This will send a request to site moderators for the ability to list shows
    and invite other artists to the platform. Please enter a website or social
    media handle where we can reach out to verify your identity.
</p>

{% for field in request_artist_form %}
    <div class="fieldgroup flex flex-col">
        {{ field.as_field_group }}
    </div>
{% endfor %}

app/findshows/templates/findshows/htmx/temp_artist_form.html
{% for field in temp_artist_form %}
    <div class="flex flex-col fieldgroup">
        {{ field.as_field_group }}
    </div>
{% endfor %}

app/findshows/templates/findshows/htmx/venue_search_results.html
{% for venue in venues %}
    <li class="menuitem hover:text-clickable-h"
        @click="select_venue('{{venue.name|escapejs}}', '{{venue.id}}', {{venue.is_verified|yesno:"true,false"}}, {{venue.declined_listing|yesno:"true,false"}})"
    >
        {{venue.name}}
    </li>
{% endfor %}

app/findshows/templates/findshows/htmx/venue_verification.html
<div class="venue-verification flex flex-col">
    {% if venue.declined_listing %}
        Declined listing
    {% elif venue.is_verified %}
        Verified
    {% else %}
        <form type="post">
            {% csrf_token %}
            <input class="btn"
                   type="button"
                   name="verify-venue"
                   hx-post="{% url 'findshows:venue_verification' venue.id %}"
                   hx-trigger="click"
                   value="Verify"
                   hx-target="closest .venue-verification"
                   hx-swap="outerHTML"
                   hx-vals='{"action": "verify"}'
            >
            <input class="btn"
                   type="button"
                   name="decline-venue"
                   hx-post="{% url 'findshows:venue_verification' venue.id %}"
                   hx-trigger="click"
                   value="Declined"
                   hx-target="closest .venue-verification"
                   hx-swap="outerHTML"
                   hx-vals='{"action": "decline"}'
            >
        </form>
    {% endif %}
</div>