app/findshows/urls.py
from functools import partial

from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "findshows"
urlpatterns = [
    path("", views.home, name="home"),
    path("user_settings", views.user_settings, name="user_settings"),
    path('about/', TemplateView.as_view(template_name='findshows/pages/about.html'), name="about"),
    path('artist_faq/', TemplateView.as_view(template_name='findshows/pages/artist_faq.html'), name="artist_faq"),
    path('contact/', views.contact, name="contact"),

    path("artist/<int:pk>", views.view_artist, name="view_artist"),
    path("artist/<int:pk>/edit", views.edit_artist, name="edit_artist"),
    path("artist_dashboard", views.artist_dashboard, name="artist_dashboard"),
    path("link_artist", views.link_artist, name="link_artist"),

    path("concert/<int:pk>", views.view_concert, name="view_concert"),
    path("concert/<int:pk>/edit", views.edit_concert, name="edit_concert"),
    path("concert/create", views.edit_concert, name="create_concert"),
    path("concert/<int:pk>/cancel", views.cancel_concert, name="cancel_concert"),
    path("concert/<int:pk>/uncancel", partial(views.cancel_concert, uncancel=True), name="uncancel_concert"),

    path("mod_dashboard", views.mod_dashboard, name="mod_dashboard"),
    path("htmx/mod_daily_digest", views.mod_daily_digest, name="mod_daily_digest"),
    path("htmx/mod_queue", views.mod_queue, name="mod_queue"),
    path("htmx/mod_outstanding_invites", views.mod_outstanding_invites, name="mod_outstanding_invites"),
    path("htmx/venue_verification/<int:pk>", views.venue_verification, name="venue_verification"),
    path("htmx/resend_invite/<int:pk>", views.resend_invite, name="resend_invite"),
    path("htmx/approve_artist_request/<int:pk>", views.approve_artist_request, name="approve_artist_request"),

    path("htmx/concert_search/", views.concert_search, name="concert_search"),

    path("htmx/mb_artist_search_results/", views.musicbrainz_artist_search_results, name="musicbrainz_artist_search_results"),
    path("htmx/venue_search_results/", views.venue_search_results, name="venue_search_results"),
    path("htmx/create_venue/", views.create_venue, name="create_venue"),
    path("htmx/create_temp_artist/", views.create_temp_artist, name="create_temp_artist"),
    path("htmx/request_artist_access/", views.request_artist_access, name="request_artist_access"),
    path("htmx/manage_artist_access/<int:pk>", views.manage_artist_access, name="manage_artist_access"),
    path("htmx/artist_search_results/", views.artist_search_results, name="artist_search_results"),
]

app/localmusic/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from findshows import views

urlpatterns = [
    path('', include("findshows.urls")),

    path('admin/', admin.site.urls),

    path("accounts/", include("django.contrib.auth.urls")),
    # accounts/login/ [name='login']
    # accounts/logout/ [name='logout']
    # accounts/password_change/ [name='password_change']
    # accounts/password_change/done/ [name='password_change_done']
    # accounts/password_reset/ [name='password_reset']
    # accounts/password_reset/done/ [name='password_reset_done']
    # accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
    # accounts/reset/done/ [name='password_reset_complete']
    path("accounts/create_account", views.create_account, name='create_account'),
    path("accounts/verify_email", views.verify_email, name='verify_email'),
    path("accounts/resend_email_verification", views.resend_email_verification, name='resend_email_verification'),

    path('captcha/', include("captcha.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/localmusic/base.html
{% load static %}
{% load findshows_tags %}
<!doctype html>
<html lang="">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <title> {% block subtitle %} {% endblock %} {% custom_text 'ST' %}</title>

        {# HTMX https://htmx.org/ #}
        <script src="https://unpkg.com/htmx.org@2.0.4"></script>
        {# Alpine plugins (load BEFORE core)#}
        <script defer src="https://cdn.jsdelivr.net/npm/@alpinejs/mask@3.x.x/dist/cdn.min.js"></script>
        <script defer src="https://cdn.jsdelivr.net/npm/@alpinejs/focus@3.x.x/dist/cdn.min.js"></script>
        {# Alpine core https://alpinejs.dev/ #}
        <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.14.8/dist/cdn.min.js"></script>
        {# Rough.js #}
        <script src="https://unpkg.com/roughjs@latest/bundled/rough.js"></script>
        {# Tailwind https://tailwindcss.com/docs/transition-property #}
        <link rel="stylesheet" href="{% static 'findshows/tailwind.css' %}">

        {# necessary for Alpine to use x-cloak #}
        <style>
         [x-cloak] {
             display: none;
         }
        </style>
    </head>
    <body>
        <div class="font-body font-stretch-90% flex flex-col min-h-screen bg-background">
            <div>
                {% include "./nav_bar.html" %}
            </div>
            <div class="flex-1">
                {% block content %}
                {% endblock %}
            </div>
            <div class="flex-shrink-0">
                {% include "./footer.html" %}
            </div>
        </div>
    </body>

    <script src='{% static "findshows/js/rough_classes.js" %}'></script>
    {# loading date picker here because it was doing weird shit when loaded by htmx #}
    <script src='{% static "findshows/js/date_picker_data.js" %}'></script>

</html>

app/templates/localmusic/footer.html
<div class="flex p-2 space-x-5">
    <div>
        <a class="link" href="{% url 'findshows:about' %}">About</a>
    </div>
    <div>
        <a class="link" href="{% url 'findshows:contact' %}">Support/Contact</a>
    </div>
</div>

app/templates/localmusic/nav_bar.html
{% load findshows_tags %}

<div class="flex h-8 mt-2 px-3 justify-between">
    <div class="basis-0 sm:grow"></div>
    <div class="self-center
                text-left text-2xl font-stretch-[30%] font-thin
                sm:text-center sm:font-stretch-100% sm:font-extralight">
        <a href="{% url 'findshows:home' %}">{% custom_text 'ST' %}</a>
    </div>
    <div class="grow flex justify-end min-w-0">
        {% if user.is_authenticated %}
            {# Dropdown menu #}
            <div class=""
                 x-data="{'show_menu': false}">
                <svg class="clickable-svg h-8 p-1 stroke-3" {# h-full breaks on mobile #}
                     viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"
                     @click="show_menu = true">
                    <line x1="0" y1="4" x2="24" y2="4" stroke="currentColor"/>
                    <line x1="0" y1="12" x2="24" y2="12" stroke="currentColor"/>
                    <line x1="0" y1="20" x2="24" y2="20" stroke="currentColor"/>
                </svg>
                <ul class="absolute right-2 top-10 popup-menu w-48 text-right"
                    x-show="show_menu"
                    @click.away="show_menu = false"
                    @keydown.escape.window="show_menu = false"
                >
                    {% if user.userprofile.managed_artists.all|length > 0 %}
                        <li class="even:bg-sub-background">
                            <a class="block link py-1 px-2" href="{% url 'findshows:artist_dashboard' %}">Artist dashboard</a>
                        </li>
                    {% endif %}
                    {% if user.is_mod %}
                        <li class="even:bg-sub-background">
                            <a class="block link py-1 px-2" href="{% url 'findshows:mod_dashboard' %}">Mod dashboard</a>
                        </li>
                    {% endif %}
                    {% if user.is_staff %}
                        <li class="even:bg-sub-background">
                            <a class="block link py-1 px-2" href="{% url 'admin:index' %}">Admin site</a>
                        </li>
                    {% endif %}
                    <li class="even:bg-sub-background">
                        <a class="block link py-1 px-2" href="{% url 'findshows:user_settings' %}">Settings</a>
                    </li>
                    <li class="even:bg-sub-background">
                        <form id="logout-form" method="post" action="{% url 'logout' %}">
                            {% csrf_token %}
                            <button class="block link py-1 px-2 w-full h-full text-right" type="submit">Log out</button>
                        </form>
                    </li>
                </ul>
            </div>
        {% else %}
            <a class="link h-fit" href="{% url 'login' %}">Log in</a>
        {% endif %}
    </div>
</div>

{% custom_text 'BR' as banner_text %}
{% if banner_text %}
    <div class="banner">
        {{ banner_text }}
    </div>
{% endif %}

app/templates/localmusic/small_page.html
{% extends "localmusic/base.html" %}

{% block content %}
    <div class="mx-3">
        <div class="bg-background border-6 border-highlight-item max-w-2xl shadow-2xl p-3 mx-auto mt-6">
            {% block small_content %}
            {% endblock %}
        </div>
    </div>
{% endblock %}